[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"


[template.environment]
  STRIPE_SECRET_KEY = "Paste your Stripe secret key here in Netlify. Do not put it in index.html."

# deploy
